spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.f4d95ed86026b6fe
            client-secret: 874d1799c65a86ed754f70c606c317a141e5f232
  data:
    cassandra:
      keyspace-name: main
      username: jRPlzAtFPldDFxtxlgUvgdBD
      password: 12csnrYyZ1EJyo1CFDzBjaEA-Xi3JbeqWIJx0y.mXZX+jmQ8mM1dwx.k2z8LGiSQB_ctp6skw-U,9N4f1tjAlsd9L,l,1m3wZXTxZNaL8wTlzmxHrPQ,eAh88UvR.nl,
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
astra.db:
    id: 7506257d-7f4f-4165-997e-649fa6fd4344-1
    region: asia-south1
    keyspace: main
    application.token: AstraCS:jRPlzAtFPldDFxtxlgUvgdBD:f023e944ec54aeaeb7f5a727424f35b7612cd9c7a52d3e3669564f5b32d4ed46
datastax.astra:
    secure-connect-bundle: secure-connect-inbox.zip
